# Edit this configuration file to define what should be installed on
# your system. Help is available in the configuration.nix(5) man page, on
# https://search.nixos.org/options and in the NixOS manual (`nixos-help`).

{
  config,
  lib,
  pkgs,
  sshPublicKey,
  ...
}:

{
  imports = [
    # Include the results of the hardware scan.
    ./hardware-configuration.nix
  ];

  nix.settings.experimental-features = [
    "nix-command"
    "flakes"
  ];

  # Bootloader
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.supportedFilesystems = [ "zfs" ];

  networking.hostName = "gullywash";
  networking.networkmanager.enable = true;
  # Necessary for ZFS, value is not important because disks won't be shared across the network
  networking.hostId = "deadbeef";
  networking.enableIPv6 = false;

  networking.firewall = {
    enable = true;
    allowedTCPPorts = [
      80 # HTTP
      443 # HTTPS
    ];
    allowedUDPPorts = [ 51820 ]; # Wireguard tunnel
  };

  time.timeZone = "Europe/Paris";

  programs.zsh.enable = true;
  users.users.guillaume = {
    isNormalUser = true;
    extraGroups = [
      "wheel"
      "docker"
    ];
    openssh.authorizedKeys.keys = [
      sshPublicKey
      # iOS
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL7HYd69a2jjU+zZ3Vztr5IsFP4PC13ps34OZcLcz5mF Generated By Termius"
    ];
    shell = pkgs.zsh;
  };

  environment.systemPackages = with pkgs; [
    neovim
    wget
    zfs
    smartmontools

    home-manager
    docker-compose
  ];

  programs.nix-ld.enable = true;
  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = false;
      StreamLocalBindUnlink = true;
    };
  };
  programs.gnupg.agent = {
    enable = true;
  };

  virtualisation.containers.enable = true;
  virtualisation.docker.enable = true;

  system.stateVersion = "24.11"; # Don't touch this ever
}
