{ self, inputs, ... }:
{
  flake.modules.nixos.gullywash =
    { pkgs, ... }:
    {
      imports = [
        self.modules.nixos.base
        self.modules.nixos.home-manager
        ./_hardware.nix
        ./_zfs.nix
      ];

      home-manager.users.guillaume = {
        imports = [ self.modules.homeManager.guillaume-headless ];
      };

      boot.loader.systemd-boot.enable = true;
      boot.loader.efi.canTouchEfiVariables = true;
      boot.supportedFilesystems = [ "zfs" ];

      networking.hostName = "gullywash";
      networking.networkmanager.enable = true;
      networking.hostId = "deadbeef";
      networking.enableIPv6 = false;

      networking.firewall = {
        enable = true;
        allowedTCPPorts = [
          80
          443
        ];
        allowedUDPPorts = [ 51820 ];
      };

      users.users.guillaume.openssh.authorizedKeys.keys = [
        (inputs.nixpkgs.lib.trim (builtins.readFile ../../headless/guiom_ssh.pub))
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIw2Cng6gQwqvu/81wWMaJUjImeMSrMQH3V/8bAJQtTE Generated By Termius"
      ];

      environment.systemPackages = with pkgs; [
        neovim
        zfs
        smartmontools
        docker-compose
      ];

      services.openssh = {
        enable = true;
        settings = {
          PasswordAuthentication = false;
          StreamLocalBindUnlink = true;
        };
      };

      programs.gnupg.agent.enable = true;

      services.fail2ban.enable = true;

      services.logrotate = {
        enable = true;
        settings = {
          "/var/log/memory-monitor.log" = {
            size = "2G";
            rotate = 5;
            missingok = true;
            notifempty = true;
            create = "644 root root";
            copytruncate = true;
          };
        };
      };

      virtualisation.containers.enable = true;

      systemd.services.config-backup = {
        description = "Backup configs directory to ZFS";
        serviceConfig = {
          Type = "oneshot";
          User = "root";
          ExecStart = "${pkgs.rsync}/bin/rsync -av --delete /opt/configs/ /configs/";
        };
      };

      systemd.timers.config-backup = {
        description = "Run config backup daily";
        wantedBy = [ "timers.target" ];
        timerConfig = {
          OnCalendar = "daily";
          Persistent = true;
          RandomizedDelaySec = "1h";
        };
      };

      system.stateVersion = "24.11";
    };

  flake.nixosConfigurations.gullywash = inputs.nixpkgs.lib.nixosSystem {
    modules = [
      self.modules.nixos.gullywash
      {
        nixpkgs.overlays = [ self.overlays.default ];
      }
    ];
  };
}
