//! The `.envrc` side of a session: what carries the workspace's own environment
//! — its flake, its tooling — into a directory that is not inside it.
//!
//! The session root is not its business. A directory-scoped variable is unset
//! again the moment a shell leaves the directory, which is the opposite of what a
//! session root has to do; that lives in the zellij layout instead (see
//! `layout`), and member repos are left exactly as they are in the main checkout.

use std::path::Path;

use anyhow::{Context, Result};

use crate::config::Config;

/// Generated, never copied from the workspace.
pub const FILE: &str = ".envrc";

const HEADER: &str = "# generated by zwt — `zwt sync --fix` rewrites it";

/// What a session's `.envrc` must contain.
pub fn session_contents(cfg: &Config) -> String {
    let mut out = format!("{HEADER}\n");
    let workspace = cfg.workspace.join(FILE);
    if workspace.exists() {
        out.push_str(&format!(
            "source_env {}\n",
            quote(&workspace.to_string_lossy())
        ));
    }
    out
}

pub fn write_session(cfg: &Config, session: &Path) -> Result<()> {
    let path = session.join(FILE);
    std::fs::write(&path, session_contents(cfg))
        .with_context(|| format!("failed to write {}", path.display()))
}

/// Whether the session's `.envrc` is the one zwt would write now: a workspace that
/// gained or moved its own `.envrc` makes an older one wrong.
pub fn session_is_current(cfg: &Config, session: &Path) -> bool {
    std::fs::read_to_string(session.join(FILE))
        .map(|found| found == session_contents(cfg))
        .unwrap_or(false)
}

fn quote(raw: &str) -> String {
    format!("'{}'", raw.replace('\'', r"'\''"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn quoting_survives_apostrophes() {
        assert_eq!(quote("/home/a b/.envrc"), "'/home/a b/.envrc'");
        assert_eq!(quote("/tmp/it's/.envrc"), r"'/tmp/it'\''s/.envrc'");
    }
}
