//! The `.envrc` side of a session: what points `WORKSPACE_ROOT` at the session
//! instead of the workspace it mirrors, so anything resolving paths against that
//! root lands in the session's own repos.
//!
//! direnv rather than an exported variable, so that any shell entering the
//! directory gets it, however it was started.

use std::path::Path;

use anyhow::{Context, Result};

use crate::config::Config;

/// Generated, never copied from the workspace.
pub const FILE: &str = ".envrc";

const HEADER: &str = "# generated by zwt — `zwt sync --fix` rewrites it";

/// The line a member repo needs so the session root's `.envrc` reaches it: direnv
/// loads only the nearest one. Repo `.envrc`s are inconsistent about naming their
/// parent, and are git-ignored, so a session's copy can be fixed up.
const SOURCE_UP: &str = "source_up_if_exists";

/// What a session's `.envrc` must contain.
///
/// `expand_path .` resolves against the file's own directory, so the value is the
/// session root however direnv reached the file. The export comes last so the
/// workspace's own `.envrc` cannot overwrite it.
pub fn session_contents(cfg: &Config) -> String {
    let mut out = format!("{HEADER}\n");
    let workspace = cfg.workspace.join(FILE);
    if workspace.exists() {
        out.push_str(&format!(
            "source_env {}\n",
            quote(&workspace.to_string_lossy())
        ));
    }
    out.push_str("export WORKSPACE_ROOT=\"$(expand_path .)\"\n");
    out
}

pub fn write_session(cfg: &Config, session: &Path) -> Result<()> {
    let path = session.join(FILE);
    std::fs::write(&path, session_contents(cfg))
        .with_context(|| format!("failed to write {}", path.display()))
}

/// Whether the session's `.envrc` is the one zwt would write now: a workspace that
/// gained or moved its own `.envrc` makes an older one wrong.
pub fn session_is_current(cfg: &Config, session: &Path) -> bool {
    std::fs::read_to_string(session.join(FILE))
        .map(|found| found == session_contents(cfg))
        .unwrap_or(false)
}

/// True when a member's `.envrc` never reaches the session root, and so runs
/// without `WORKSPACE_ROOT`. A repo with no `.envrc` at all has nothing to fix.
pub fn member_is_orphaned(worktree: &Path) -> bool {
    match std::fs::read_to_string(worktree.join(FILE)) {
        Ok(found) => !reaches_parent(&found),
        Err(_) => false,
    }
}

pub fn link_member(worktree: &Path) -> Result<bool> {
    let path = worktree.join(FILE);
    let Ok(found) = std::fs::read_to_string(&path) else {
        return Ok(false);
    };
    if reaches_parent(&found) {
        return Ok(false);
    }
    std::fs::write(&path, format!("{SOURCE_UP}\n{found}"))
        .with_context(|| format!("failed to write {}", path.display()))?;
    Ok(true)
}

fn reaches_parent(contents: &str) -> bool {
    contents.lines().any(|line| {
        let line = line.trim();
        if line.starts_with('#') {
            return false;
        }
        if line.starts_with("source_up") {
            return true;
        }
        let named = line
            .strip_prefix("source_env_if_exists ")
            .or_else(|| line.strip_prefix("source_env "));
        match named {
            Some(arg) => matches!(
                arg.trim().trim_matches(['"', '\'']),
                ".." | "../" | "../.envrc"
            ),
            None => false,
        }
    })
}

fn quote(raw: &str) -> String {
    format!("'{}'", raw.replace('\'', r"'\''"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn only_a_real_parent_reference_counts() {
        assert!(reaches_parent("source_up_if_exists\nuse flake ../flake"));
        assert!(reaches_parent(
            "use flake ../flake#lib\nsource_env ../.envrc"
        ));
        assert!(!reaches_parent("use flake ../flake#lib"));
        assert!(!reaches_parent("# source_up_if_exists\nuse flake ./flake"));
        // A sibling, not a parent: it brings no WORKSPACE_ROOT.
        assert!(!reaches_parent("source_env ../docs/.envrc"));
    }

    #[test]
    fn quoting_survives_apostrophes() {
        assert_eq!(quote("/home/a b/.envrc"), "'/home/a b/.envrc'");
        assert_eq!(quote("/tmp/it's/.envrc"), r"'/tmp/it'\''s/.envrc'");
    }
}
