//! The zellij layout a session is attached with, and the one place
//! `WORKSPACE_ROOT` is set for a whole session.
//!
//! A pane's environment is fixed when the zellij server starts and zellij keeps
//! no per-session environment of its own: there is no `set-env` action, and an
//! `env` block in the layout zellij serializes for resurrection is ignored. So
//! the value has to be handed to the server on every attach — `--layout` applies
//! it both when creating a session and when resurrecting one — which is what
//! makes it a property of the session rather than of a directory.
//!
//! Nothing here describes tabs or panes. A layout that named the members would
//! have to be rewritten by `add` and `promote`, and splits are not zwt's to
//! decide; `layout { pane }` is what zellij would have done anyway.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

/// Generated, inside the marker's directory: it is state describing the session,
/// not configuration.
pub const FILE: &str = ".zwt/layout.kdl";

const HEADER: &str = "// generated by zwt — `zwt sync --fix` rewrites it";

pub fn path(session: &Path) -> PathBuf {
    session.join(FILE)
}

/// `cwd` makes the session root what a pane opens in, and the `env` block is the
/// point of the file.
pub fn contents(session: &Path) -> String {
    let root = kdl_string(&session.to_string_lossy());
    format!(
        "{HEADER}\n\
         layout {{\n\
        \x20   cwd {root}\n\
        \x20   pane\n\
         }}\n\
         env {{\n\
        \x20   WORKSPACE_ROOT {root}\n\
         }}\n"
    )
}

pub fn write(session: &Path) -> Result<()> {
    let file = path(session);
    let dir = file.parent().expect("layout path has a parent");
    std::fs::create_dir_all(dir).with_context(|| format!("failed to create {}", dir.display()))?;
    std::fs::write(&file, contents(session))
        .with_context(|| format!("failed to write {}", file.display()))
}

/// Whether the layout is the one zwt would write now: a session that moved has
/// an older one pointing somewhere else.
pub fn is_current(session: &Path) -> bool {
    std::fs::read_to_string(path(session))
        .map(|found| found == contents(session))
        .unwrap_or(false)
}

fn kdl_string(raw: &str) -> String {
    format!("\"{}\"", raw.replace('\\', r"\\").replace('"', "\\\""))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_root_is_both_the_cwd_and_the_exported_value() {
        let out = contents(Path::new("/home/g/work/sessions/proj-1"));
        assert!(out.contains("cwd \"/home/g/work/sessions/proj-1\""));
        assert!(out.contains("WORKSPACE_ROOT \"/home/g/work/sessions/proj-1\""));
    }

    #[test]
    fn quoting_survives_a_path_kdl_would_misread() {
        assert_eq!(kdl_string(r#"/tmp/a "b"/c"#), r#""/tmp/a \"b\"/c""#);
        assert_eq!(kdl_string(r"/tmp/a\b"), r#""/tmp/a\\b""#);
    }
}
