{ inputs, ... }:
{
  flake.modules.homeManager.quickshell =
    { pkgs, config, lib, ... }:
    let
      quickshell = inputs.quickshell.packages.${pkgs.stdenv.hostPlatform.system}.default;

      # Same trick as the eww module: glyphs are decoded from JSON escapes in Nix
      # so the QML sources stay ASCII (literal nerd-font glyphs get stripped by
      # some edits, leaving zero-width icons). JSON has no \UXXXXXXXX escape, so
      # astral-plane codepoints go in as UTF-16 surrogate pairs.
      hex4 = n: lib.fixedWidthString 4 "0" (lib.toHexString n);
      glyph =
        hexcp:
        let
          cp = lib.fromHexString hexcp;
          c = cp - 65536;
        in
        if cp < 65536 then
          builtins.fromJSON ''"\u${hex4 cp}"''
        else
          builtins.fromJSON ''"\u${hex4 (55296 + c / 1024)}\u${hex4 (56320 + lib.mod c 1024)}"'';

      # The one compiled component, shared with the eww bar: a single niri IPC tap
      # that keeps the layout model in memory and prints a snapshot line only when
      # it changes. Quickshell reads those lines with a SplitParser.
      niriState = pkgs.rustPlatform.buildRustPackage {
        pname = "niri-state";
        version = "0.1.0";
        src = ../eww/niri-state;
        cargoLock.lockFile = ../eww/niri-state/Cargo.lock;
      };

      claudeUsage = pkgs.writeShellScriptBin "claude-usage-qs" ''
        export PATH="${lib.makeBinPath [ pkgs.jq ]}:$PATH"
        exec ${pkgs.bash}/bin/bash ${../bar-scripts/claude-usage.sh} "$@"
      '';

      # nf-md-* codepoints live above the BMP; `glyph` handles the surrogate pair.
      glyphs = {
        calendar = glyph "F00F0";
        clockAlt = glyph "F0954";
        disk = glyph "F02CA";
        cpu = glyph "F035B";
        ram = glyph "F061A";
        zram = glyph "F140B";
        claude = glyph "F0721";
        gear = glyph "F0493";
        record = glyph "F111";
        volLow = glyph "F057F";
        volMid = glyph "F0580";
        volHigh = glyph "F057E";
        volMuted = glyph "F075F";
        batHigh = glyph "F12A3";
        batMedium = glyph "F12A2";
        batLow = glyph "F12A1";
        batCharging = glyph "F0084";
        idle = glyph "F06E";
        dnd = glyph "F1F6";
        saver = glyph "F0F86";
        balanced = glyph "F0F85";
        performance = glyph "F04C5";
        play = glyph "F04B";
        pause = glyph "F04C";
        prev = glyph "F048";
        next = glyph "F051";
        spotify = glyph "F1BC";
        firefox = glyph "F269";
        chrome = glyph "F268";
        movie = glyph "F0381";
        music = glyph "F001";
        larrow = builtins.fromJSON ''"\u2039"'';
        rarrow = builtins.fromJSON ''"\u203a"'';
      };

      configQml = pkgs.writeText "Config.qml" ''
        pragma Singleton
        // Generated by modules/gui/quickshell/default.nix. Absolute store paths and
        // pre-decoded glyphs, so no QML source depends on PATH or carries a
        // private-use character.
        import Quickshell

        Singleton {
            readonly property string niriState: "${niriState}/bin/niri-state"
            readonly property string niri: "${pkgs.niri}/bin/niri"
            readonly property string claudeUsage: "${claudeUsage}/bin/claude-usage-qs"
            readonly property string pavucontrol: "${pkgs.pavucontrol}/bin/pavucontrol"
            readonly property string makoctl: "${pkgs.mako}/bin/makoctl"
            readonly property string screenrecord: ${builtins.toJSON config.screenrecordScreenTool}
            readonly property string systemdInhibit: "${pkgs.systemd}/bin/systemd-inhibit"
            readonly property string sleepBin: "${pkgs.coreutils}/bin/sleep"
            readonly property string df: "${pkgs.coreutils}/bin/df"

            readonly property var glyph: ${builtins.toJSON glyphs}
        }
      '';

      shellDir = pkgs.runCommandLocal "quickshell-bar" { } ''
        cp -r ${./qml} $out
        chmod -R u+w $out
        cp ${configQml} $out/Config.qml
      '';
    in
    {
      home.packages = [ quickshell ];

      xdg.configFile."quickshell/bar".source = shellDir;

      # Not wanted by graphical-session.target yet: the eww bar still owns the
      # session, and two bars would both claim an exclusive zone. Start manually
      # with `systemctl --user start quickshell`.
      systemd.user.services.quickshell = {
        Unit = {
          Description = "quickshell bar";
          PartOf = [ "graphical-session.target" ];
          After = [ "graphical-session.target" ];
        };
        Service = {
          ExecStart = "${quickshell}/bin/qs -c bar";
          Restart = "on-failure";
        };
      };
    };
}
